### ISSUE TITLE
Do you have more infos/schematics?

### ISSUE THREAD

**Issue by benbender** [ChadMatsalla/esphome-delonghi-dedica#1]
Hey, cool project! I just wanted to hear if you happen to have some kind of schematics/pinouts/infos for the dedica as I'm going to do basically the same as you. And if you already did the work it would be very kind if you could upload the info. 

Best

**Comment by ChadMatsalla** [comment]
I'm travelling at the moment but I'll post some photos as soon as I find them on my phone.

Remove the silver lid from the unit and look for the connector. There are three wires of interest. Short the first to the second and button one seems pressed. Short the first to the third and button two seems pressed. I installed relays to short those wires, and used esphome to program the esp to connect to homeassistant to provide the remote.

**Comment by ChadMatsalla** [comment]
I included a file in images/IMG_1223.JPG . I'll try to rename it later.

The image shows an XH 2.54 connector with three wires labelled with tape. i think that the black wire is ground. Short black to red and button one pressed. Short black to yellow and button two is pressed. Please correct me if I'm wrong.

**Comment by benbender** [comment]
Hey, thank you very much! I'll look if I can replicate your setup! On that note, I think there would be quite a bit of interest if you would finish up the documentation of your project! Cheers!
